let cocteles = [
    {   
        id: 1,
        nombre: "Margarita",
        precio: 5,
        licor: "Tequila",
        stock: 30,
        plan: "Plan Basico",
        disponible: true,
        cristaleria: "Copa Coupe",
        imagenes: "https://i2.wp.com/www.downshiftology.com/wp-content/uploads/2019/05/Margarita-10.jpg"
    },
    {   
        id: 2,
        nombre: "Daikiri",
        precio: 5,
        licor: "Ron",
        stock: 25,
        plan: "Plan Basico",
        disponible: false,
        cristaleria: "Copa Martini",
        imagenes: "https://trinkreif.de/wp-content/uploads/original-daiquiri-cocktail-rezept.jpg",
    },
    {   
        id: 3,
        nombre: "Moscow Mule",
        precio: 7,
        licor: "Vodka",
        stock: 35,
        plan: "Plan Premium",
        disponible: true,
        cristaleria: "Vaso Corto",
        imagenes: "https://cf.ltkcdn.net/cocktails/images/std/283495-800x533-classic-moscow-mule-cocktail.jpg",
    },
    {   
        id: 4,
        nombre: "Negroni",
        precio: 7,
        licor: "Ginebra",
        stock: 20,
        plan: "Plan Premium",
        disponible: false,
        cristaleria: "Vaso Corto",
        imagenes: "https://cocktaildb.com/wp-content/uploads/2022/05/Classic-Negroni-Cocktail-Recipe.jpg",
    },
    {   
        id: 5,
        nombre: "Aperol Spritz",
        precio: 9,
        licor: "Aperol",
        stock: 15,
        plan: "Plan VIP",
        disponible: true,
        cristaleria: "Copa Ballon",
        imagenes: "https://www.bhg.com/thmb/CftyswU9XF4XmGbB8hwonayP7Oc=/2250x0/filters:no_upscale():strip_icc()/Aperol-Spritz-Cocktail-6750788-fd60c0f0e6614cbcb4acc9f8d638ab56.jpg",
    },
    {   
        id: 6,
        nombre: "Old Fashioned",
        precio: 9,
        licor: "Bourbon",
        stock: 22,
        plan: "Plan VIP",
        disponible: true,
        cristaleria: "Vaso Corto",
        imagenes: "https://www.simplyrecipes.com/thmb/s_de1Nuw4ULiHNECVHOCBY5u5Wk=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/__opt__aboutcom__coeus__resources__content_migration__simply_recipes__uploads__2020__01__Old-Fashioned-Cocktail-LEAD-5-1024x681-aa81a798a156453d80d1f7d41de893ff.jpg",
    },
];